#############################################################################
# Makefile for building: Interface.app/Contents/MacOS/Interface
# Generated by qmake (3.0) (Qt 5.5.0)
# Project:  Interface.pro
# Template: app
# Command: /Users/hiroka/Qt5.5.0/5.5/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile Interface.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_QUICK_LIB -DQT_WEBKITWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_SCRIPT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../../Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/Headers -I../../../Qt5.5.0/5.5/clang_64/lib/QtWebKitWidgets.framework/Headers -I../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers -I../../../Qt5.5.0/5.5/clang_64/lib/QtWebKit.framework/Headers -I../../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers -I../../../Qt5.5.0/5.5/clang_64/lib/QtQml.framework/Headers -I../../../Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/Headers -I../../../Qt5.5.0/5.5/clang_64/lib/QtScript.framework/Headers -I../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../../Qt5.5.0/5.5/clang_64/mkspecs/macx-clang -F/Users/hiroka/Qt5.5.0/5.5/clang_64/lib
QMAKE         = /Users/hiroka/Qt5.5.0/5.5/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Interface1.0.0
DISTDIR = /Users/hiroka/Documents/QT/Interface/.tmp/Interface1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -stdlib=libc++ -mmacosx-version-min=10.7 -Wl,-rpath,/Users/hiroka/Qt5.5.0/5.5/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/hiroka/Qt5.5.0/5.5/clang_64/lib -framework QtQuick -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtQml -framework QtNetwork -framework QtWebKitWidgets -framework QtWidgets -framework QtWebKit -framework QtScript -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp qrc_image.cpp \
		moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		qrc_image.o \
		moc_mainwindow.o
DIST          = ../../../Qt5.5.0/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/qdevice.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/device_config.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/common/unix.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/common/mac.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/common/macx.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/common/clang.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/qconfig.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/default_post.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/c++11.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/declarative_debug.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/qt.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/resources.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/moc.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/uic.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/yacc.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/lex.prf \
		Interface.pro mainwindow.h main.cpp \
		mainwindow.cpp
QMAKE_TARGET  = Interface
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Interface.app/Contents/MacOS/Interface

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk \
		-std=c++11 \
		-stdlib=libc++ \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d Interface.app/Contents/MacOS/ || mkdir -p Interface.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Interface.pro ../../../Qt5.5.0/5.5/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt5.5.0/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/qdevice.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/device_config.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/common/unix.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/common/mac.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/common/macx.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/common/clang.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/qconfig.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/default_post.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/c++11.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/declarative_debug.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/qt.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/resources.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/moc.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/uic.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/yacc.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/lex.prf \
		Interface.pro \
		image.qrc \
		/Users/hiroka/Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/QtQuick.prl \
		/Users/hiroka/Qt5.5.0/5.5/clang_64/lib/QtWebKitWidgets.framework/QtWebKitWidgets.prl \
		/Users/hiroka/Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/hiroka/Qt5.5.0/5.5/clang_64/lib/QtWebKit.framework/QtWebKit.prl \
		/Users/hiroka/Qt5.5.0/5.5/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/hiroka/Qt5.5.0/5.5/clang_64/lib/QtQml.framework/QtQml.prl \
		/Users/hiroka/Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		/Users/hiroka/Qt5.5.0/5.5/clang_64/lib/QtScript.framework/QtScript.prl \
		/Users/hiroka/Qt5.5.0/5.5/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile Interface.pro
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/qdevice.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/device_config.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/common/unix.conf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/common/mac.conf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/common/macx.conf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/common/sanitize.conf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/common/clang.conf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/qconfig.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/qt_config.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/default_pre.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/default_post.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/c++11.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/qml_debug.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/declarative_debug.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/warn_on.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/qt.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/resources.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/moc.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/uic.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/exceptions.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/yacc.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/lex.prf:
Interface.pro:
image.qrc:
/Users/hiroka/Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/QtQuick.prl:
/Users/hiroka/Qt5.5.0/5.5/clang_64/lib/QtWebKitWidgets.framework/QtWebKitWidgets.prl:
/Users/hiroka/Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/hiroka/Qt5.5.0/5.5/clang_64/lib/QtWebKit.framework/QtWebKit.prl:
/Users/hiroka/Qt5.5.0/5.5/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/hiroka/Qt5.5.0/5.5/clang_64/lib/QtQml.framework/QtQml.prl:
/Users/hiroka/Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
/Users/hiroka/Qt5.5.0/5.5/clang_64/lib/QtScript.framework/QtScript.prl:
/Users/hiroka/Qt5.5.0/5.5/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile Interface.pro

qmake_all: FORCE

Interface.app/Contents/PkgInfo: 
	@test -d Interface.app/Contents || mkdir -p Interface.app/Contents
	@$(DEL_FILE) Interface.app/Contents/PkgInfo
	@echo "APPL????" > Interface.app/Contents/PkgInfo
Interface.app/Contents/Resources/empty.lproj: 
	@test -d Interface.app/Contents/Resources || mkdir -p Interface.app/Contents/Resources
	@touch Interface.app/Contents/Resources/empty.lproj
	
Interface.app/Contents/Info.plist: 
	@test -d Interface.app/Contents || mkdir -p Interface.app/Contents
	@$(DEL_FILE) Interface.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,KNN.Interface,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,Interface,g" -e "s,@TYPEINFO@,????,g" ../../../Qt5.5.0/5.5/clang_64/mkspecs/macx-clang/Info.plist.app >Interface.app/Contents/Info.plist

all: Makefile \
		Interface.app/Contents/PkgInfo \
		Interface.app/Contents/Resources/empty.lproj \
		Interface.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents image.qrc $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Interface.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all: qrc_image.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_image.cpp
qrc_image.cpp: image.qrc \
		MilaOCR3.png \
		export.png \
		OCRImg.png \
		importfile.png \
		MilaOCR.png
	/Users/hiroka/Qt5.5.0/5.5/clang_64/bin/rcc -name image image.qrc -o qrc_image.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: ../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QProcess \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qprocess.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QHBoxLayout \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QVBoxLayout \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/QImage \
		../../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QCheckBox \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qcheckbox.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		../../../Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/Headers/QNetworkRequest \
		../../../Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/Headers/qnetworkrequest.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/Headers/QNetworkReply \
		../../../Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QUrl \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qurl.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QEvent \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qcoreevent.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QJsonDocument \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qjsondocument.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qjsonobject.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QJsonArray \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qjsonarray.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QList \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qlist.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/Headers/QHttpMultiPart \
		../../../Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/Headers/qhttpmultipart.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QFile \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtScript.framework/Headers/QScriptEngine \
		../../../Qt5.5.0/5.5/clang_64/lib/QtScript.framework/Headers/qscriptengine.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QDir \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QVariantMap \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QByteArray \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qbytearray.h \
		mainwindow.h
	/Users/hiroka/Qt5.5.0/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/hiroka/Qt5.5.0/5.5/clang_64/mkspecs/macx-clang -I/Users/hiroka/Documents/QT/Interface -I/Users/hiroka/Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/Headers -I/Users/hiroka/Qt5.5.0/5.5/clang_64/lib/QtWebKitWidgets.framework/Headers -I/Users/hiroka/Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/hiroka/Qt5.5.0/5.5/clang_64/lib/QtWebKit.framework/Headers -I/Users/hiroka/Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/hiroka/Qt5.5.0/5.5/clang_64/lib/QtQml.framework/Headers -I/Users/hiroka/Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/Headers -I/Users/hiroka/Qt5.5.0/5.5/clang_64/lib/QtScript.framework/Headers -I/Users/hiroka/Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/hiroka/Qt5.5.0/5.5/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/Users/hiroka/Qt5.5.0/5.5/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QProcess \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qprocess.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QHBoxLayout \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QVBoxLayout \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/QImage \
		../../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QCheckBox \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qcheckbox.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		../../../Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/Headers/QNetworkRequest \
		../../../Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/Headers/qnetworkrequest.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/Headers/QNetworkReply \
		../../../Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QUrl \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qurl.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QEvent \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qcoreevent.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QJsonDocument \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qjsondocument.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qjsonobject.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QJsonArray \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qjsonarray.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QList \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qlist.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/Headers/QHttpMultiPart \
		../../../Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/Headers/qhttpmultipart.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QFile \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtScript.framework/Headers/QScriptEngine \
		../../../Qt5.5.0/5.5/clang_64/lib/QtScript.framework/Headers/qscriptengine.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QDir \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QVariantMap \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QByteArray \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qbytearray.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QProcess \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qprocess.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QHBoxLayout \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QVBoxLayout \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/QImage \
		../../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/QCheckBox \
		../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers/qcheckbox.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		../../../Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/Headers/QNetworkRequest \
		../../../Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/Headers/qnetworkrequest.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/Headers/QNetworkReply \
		../../../Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QUrl \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qurl.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QEvent \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qcoreevent.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QJsonDocument \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qjsondocument.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qjsonobject.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QJsonArray \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qjsonarray.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QList \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qlist.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/Headers/QHttpMultiPart \
		../../../Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/Headers/qhttpmultipart.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QFile \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtScript.framework/Headers/QScriptEngine \
		../../../Qt5.5.0/5.5/clang_64/lib/QtScript.framework/Headers/qscriptengine.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QDir \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QVariantMap \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QByteArray \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qbytearray.h \
		ui_mainwindow.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/QIcon \
		../../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers/qicon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

qrc_image.o: qrc_image.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_image.o qrc_image.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

